---
## add authorized keys 
#- name: check {{keyfile}}
#  stat: path="{{keyfile}}"
#  ignore_errors: true
#  register: key_state
#  delegate_to: 127.0.0.1
#
#- fail: msg="{{keyfile}} does not exist"
#  when: key_state.stat.exists == false
#
#- name: read key file
#  command: cat {{keyfile}}
#  register: key_content
#  delegate_to: 127.0.0.1
#
#- name: add authorized keys for current user accounts
#  authorized_key: key="{{key_content.stdout}}" user="{{user}}" 

- name: ssh-copy-id
  command: ssh-copy-id -i {{keyfile}} {{ansible_ssh_user}}@{{inventory_hostname}}
  delegate_to: 127.0.0.1
