---
- include_vars: "{{ ansible_os_family }}.yml"
- name: install cc & gcc packages 
  action: "{{pkgmgr.pkg}} {{pkgmgr.name}}={{item}} {{pkgmgr.state}}=present"
  #action: yum name={{item}} state=present
  #action: apt pkg={{item}} state=present
  with_items:
    packages
