---
## disable requiretty
- name: disable 'requiretty' in /etc/sudoers
  lineinfile:
    dest: "{{sudoers}}"
    state: absent
    regexp: "^Defaults\\s*requiretty"
    backup: yes
    validate: "visudo -cf %s"
  sudo: yes
  sudo_user: root
