---
# tasks file for logstash
- name: create directory
  file: path="{{base_home}}" state=directory

- name: unpack tarball to remote node
  unarchive: src="{{logstash_tarball}}" dest="{{base_home}}"

- name: check if unpack module worked
  stat: path="{{logstash_home}}"
  ignore_errors: true
  register: unpack_check

- fail: msg="unpack logstash failed!"
  when: unpack_check.stat.exists == false

- name: update ENV
  lineinfile:
    dest: "{{env_profile}}"
    line: "export PATH={{logstash_home}}/bin:$PATH"
    state: present
