---
# handlers file for neutron-logging
- name: restart neutron-server
  service: name=neutron-server state=restarted
  sudo: yes
  sudo_user: root
- name: reload neutron-server
  service: name=neutron-server state=reloaded
  sudo: yes
  sudo_user: root
