---
# tasks file for nova-logging
# add redirection rules 
- name: configure rsyslog
  lineinfile: 
    dest: "/etc/rsyslog.conf" 
    line: "{{item.value}}.* @@{{log_server}}"
    state: present
  with_dict:
    "{{nova_facility}}"
  sudo: yes
  sudo_user: root
  notify:
    - restart rsyslog

# enable use_syslog in nova.conf
- name: configure nova.conf
  lineinfile:
    dest: "{{nova_conf}}"
    regexp: "{{item.regx}}"
    line: "{{item.line}}"
    insertafter: "\\[DEFAULT\\]"
    state: present
  with_items:
    "{{lines}}"
  sudo: yes
  sudo_user: root
  notify:
    - restart nova-compute
