---
- name: lek on docker
  hosts: os-logging
  gather_facts: true
  vars:
    - host: "10.32.105.153"

  roles:
      - {role: common-env }
      - {role: nova-logging, host: "{{host}}", port: "10514" }
      - {role: cinder-logging, host: "{{host}}", port: "11514" }
      - {role: neutron-logging, host: "{{host}}", port: "12514" }
