---
- name: common settings
  hosts: lek
  gather_facts: true
  roles: 
    - {role: common-env}
    - {role: sun-jdk}

- name: setup logstash
  hosts: logstash
  gather_facts: true
  roles: 
    - {role: logstash}
      
- name: setup kibana and elasticsearch
  hosts: els
  gather_facts: true
  
  roles: 
    - {role: kibana}
    - {role: elasticsearch}
