---
# tasks file for sun-jdk
- name: create directory
  file: path="{{base_home}}" state=directory

- name: unpack tarball to remote node
  unarchive: src="{{jdk_tarball}}" dest="{{base_home}}"

- name: check if unpack module worked
  stat: path="{{java_home}}"
  ignore_errors: true
  register: unpack_check

- fail: msg="unpack jdk failed!"
  when: unpack_check.stat.exists == false

- name: create symbolic to /bin/java
  file: src="{{java_home}}/bin/java" dest=/bin/java state=link
  sudo: yes
  sudo_user: root

- name: update ENV
  lineinfile:
    dest: "{{item[0]}}"
    line: "{{item[1]}}"
    state: present
    create: yes
  with_nested:
    - ["/etc/profile", "{{ansible_env.HOME}}/.profile"]
    - ["export PATH={{java_home}}/bin:$PATH", "export JAVA_HOME={{java_home}}", "export CLASSPATH=.:{{java_home}}/lib"]
  sudo: yes
  sudo_user: root
