---
# tasks file for neutron-logging
# add redirection rules 
- name: configure rsyslog
  lineinfile: 
    dest: "/etc/rsyslog.conf" 
    line: "{{item.value}}.* @@{{log_server}}"
    state: present
  with_dict:
    "{{neutron_facility}}"
  sudo: yes
  sudo_user: root
  notify:
    - restart rsyslog

# enable use_syslog in neutron.conf
- name: configure neutron.conf
  lineinfile:
    dest: "{{neutron_conf}}"
    regexp: "{{item.regx}}"
    line: "{{item.line}}"
    state: present
    insertafter: "\\[DEFAULT\\]"
  with_items:
    "{{lines}}"
  sudo: yes
  sudo_user: root
  notify:
    - reload neutron-server
