---
- name: create directory
  file: path="{{base_home}}" state=directory

- name: unpack tarball to remote node
  unarchive: src="{{kibana_tarball}}" dest="{{base_home}}"
  tags: unpack

- name: check if unpack module worked
  stat: path="{{kibana_home}}"
  ignore_errors: true
  register: unpack_check
  tags: unpack

- fail: msg="unpack kibana failed!"
  when: unpack_check.stat.exists == false
  tags: unpack

- name: update ENV
  lineinfile:
    dest: "{{env_profile}}"
    line: "export PATH={{kibana_home}}/bin:$PATH"
    state: present

- name: remove default config/kibana.yml
  file: path="{{kibana_home}}/config/{{kibana_config}}" state=absent
  tags: config

- name: update configuration file
  template: src="{{kibana_config}}.j2" dest="{{kibana_home}}/config/{{kibana_config}}"
  tags: config
