---
# tasks file for cinder-logging
- name: configure rsyslog
  lineinfile:
    dest: "/etc/rsyslog.conf"
    line: "{{item.value}}.* @@{{log_server}}"
    state: present
  with_dict:
    "{{cinder_facility}}"
  sudo: yes
  sudo_user: root
  notify:
    - restart rsyslog

- name: configure cinder.conf
  lineinfile:
    dest: "{{cinder_conf}}"
    regexp: "{{item.regx}}"
    line: "{{item.line}}"
    state: present
  with_items:
    "{{lines}}"
  sudo: yes
  sudo_user: root
  notify:
    - restart cinder-api
    - restart cinder-volume
    - restart cinder-backup
    - restart cinder-scheduler
