---
# tasks file for etcd

- name: create directory if not exists
  file: path="{{ansible_env.HOME}}/bin" state="directory"

- name: remove old data-dir
  file: path="{{data_dir}}" state=absent

- name: copy etcd binaries
  copy: src="{{item}}" dest="{{ansible_env.HOME}}/bin/{{item}}" mode="0755"
  with_items:
    - etcd
    - etcdctl

- name: template setup script
  template: src=etcd_setup.sh.j2 dest="{{ansible_env.HOME}}/bin/etcd_setup.sh" mode="0755"

- name: setup etcd cluster
  shell: "nohup {{ansible_env.HOME}}/bin/etcd_setup.sh &"
