---
# defaults file for cinder-logging
cinder_conf: "/etc/cinder/cinder.conf"
cinder_facility:
  LOG_LOCAL1: local1
port: "10514"
host: "127.0.0.1"
log_server: "{{host}}:{{port}}"
protocal: "tcp"
lines:
  - {regx: "^verbose=", line: "verbose=False" }
  - {regx: "^debug=", line: "debug=False" }
  - {regx: "^use_syslog=", line: "use_syslog=True" }
  - {regx: "^syslog_log_facility=", line: "syslog_log_facility=LOG_LOCAL1" }
