---
- name: create directory
  file: path="{{base_home}}" state=directory

- name: unpack tarball to remote node
  unarchive: src="{{es_tarball}}" dest="{{base_home}}"
  tags: unpack

- name: check if unpack module worked
  stat: path="{{es_home}}"
  ignore_errors: true
  register: unpack_check
  tags: unpack

- fail: msg="unpack elasticsearch failed!"
  when: unpack_check.stat.exists == false
  tags: unpack

- name: update ENV
  lineinfile:
    dest: "{{env_profile}}"
    line: "export PATH={{es_home}}/bin:$PATH"
    state: present

- name: remove default config/elasticsearch.yml
  file: path="{{es_home}}/config/{{item}}" state=absent
  with_items:
    - "{{es_logging_config}}"
    - "{{es_config}}"
  tags: setup_srv

- name: update configuration file
  template: src="{{item}}.j2" dest="{{es_home}}/config/{{item}}"
  with_items:
    - "{{es_logging_config}}"
    - "{{es_config}}"
  tags: setup_srv

- name: install elasticsearch service
  template: src="{{item.src}}" dest="{{item.dest}}" mode="{{item.mode}}"
  with_items:
    - {src: "{{es_srvname}}.j2", dest: "/etc/init.d/{{es_srvname}}", mode: 755}
    - {src: "default.j2", dest: "/etc/default/{{es_srvname}}", mode: 644}
  sudo: yes
  sudo_user: root
  notify:
    - enable elasticsearch
    - restart elasticsearch
  tags: setup_srv
