---
# defaults file for etcd
exec: "{{ansible_env.HOME}}/bin/etcd"
group: "etcd-cluster"
data_dir: "{{ansible_env.HOME}}/.default.etcd"
cluster_token: "etcd-dev-cluster"
node_name: "etcd_{{ansible_hostname}}"
peer_port: 2380
client_port: 2379
peer_urls: "http://{{ansible_default_ipv4.address}}:{{peer_port}}"
client_urls: "http://{{ansible_default_ipv4.address}}:{{client_port}},http://127.0.0.1:2379"
state: "new"
